license = "MIT"

[[mods]]
modId = "custom_default_world_preset"
version = "${version}"
displayName = "Custom Default World Preset"
description = "This simple mod allows you to change the default world preset."
displayURL = "https://modrinth.com/mod/custom-default-world-preset"
authors = "MattiDragon"
logoFile = "assets/custom_default_world_preset/icon.png"
logoBlur = false

[[mixins]]
config = "custom_default_world_preset.mixins.json"

[[dependencies.custom_default_world_preset]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"

[[dependencies.custom_default_world_preset]]
modId="minecraft"
type="required"
versionRange="[26.1-snapshot-1,)"
