[versions]
minecraft = "26.1-snapshot-1"

mixin = "0.16.5+mixin.0.8.7"
mixin-extras = "0.5.0"

fabric-loader = "0.18.3"
fabric-api = "0.140.1+26.1"
fabric-loom = "1.14-SNAPSHOT"

mdg = "2.0.134"
neoforge = "26.1.0.0-alpha.1+snapshot-1"

shadow = "9.3.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixin-extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
neoforge-mdg = { id = "net.neoforged.moddev", version.ref = "mdg" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }